PROGRAM RAIZ_BISSEC
	IMPLICIT NONE
	CHARACTER(LEN=32) :: ARG
	INTEGER :: NUM_CONVERTIDO
	INTEGER :: COUNTER
	CALL GETARG(1,ARG)
	PRINT *, len(ARG)
	COUNTER = 0
	DO
		PRINT *, COUNTER
		COUNTER = COUNTER + 1
		IF(COUNTER .GT. 90) EXIT
	END DO
END PROGRAM
